//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yazlab2_1.Models.EntitiyFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilar
    {
        public int id { get; set; }
        public string isim { get; set; }
        public Nullable<int> kitap { get; set; }
        public Nullable<System.DateTime> alinan_tarih { get; set; }
        public Nullable<int> password { get; set; }
    }
}
